
import californiaVeggie from "../assets/images/california-veggie-pizza.png";
import salsicciaFriarielli from "../assets/images/salsiccia-e-friarielli-pizza.png";
import pepperoni from "../assets/images/pepperoni-pizza.png";
import detroitRedTop from "../assets/images/detroit-red-top-pizza.png";
import margherita from "../assets/images/margherita-pizza.png";
import sfincione from "../assets/images/sfincione-pizza.png";
import hawaiian from "../assets/images/hawaiian-pizza.png";
import chicagoClassic from "../assets/images/chicago-classic-pizza.png";

export let menuTab = {
   init: function() {
      this.cacheDom();
      this.render();
   },

   cacheDom: function() {
      this.content = document.querySelector("#content");
   },

   render: function() {
      this.content.innerHTML = "";

         let div = document.createElement("div");
         div.setAttribute("class", "menu");
            let div1 = document.createElement("div");
            div1.setAttribute("class", "menu__item");
               let img11 = document.createElement("img");
               img11.setAttribute("src", californiaVeggie);
               img11.setAttribute("alt", "Pizza");
               img11.setAttribute("class", "menu__item-image");
               let div11 = document.createElement("div");
               div11.setAttribute("class", "menu__item-details");
                  let h11 = document.createElement("h3");
                  h11.setAttribute("class", "menu__item-title");
                  h11.textContent = "California Veggie";
                  let p11 = document.createElement("p");
                  p11.setAttribute("class", "menu__item-description");
                  p11.textContent = "Thin crust with artichoke hearts, mushrooms, roasted peppers, and goat cheese.";
                  let p12 = document.createElement("p");
                  p12.setAttribute("class", "menu__item-price");
                  p12.textContent = "$17";
               div11.appendChild(h11);
               div11.appendChild(p11);
               div11.appendChild(p12);
            div1.appendChild(img11);
            div1.appendChild(div11);

            let div2 = document.createElement("div");
            div2.setAttribute("class", "menu__item");
               let img21 = document.createElement("img");
               img21.setAttribute("src", salsicciaFriarielli);
               img21.setAttribute("alt", "Pizza");
               img21.setAttribute("class", "menu__item-image");
               let div21 = document.createElement("div");
               div21.setAttribute("class", "menu__item-details");
                  let h21 = document.createElement("h3");
                  h21.setAttribute("class", "menu__item-title");
                  h21.textContent = "Salsiccia e Friarielli";
                  let p21 = document.createElement("p");
                  p21.setAttribute("class", "menu__item-description");
                  p21.textContent = "A 'white' pizza (no tomato sauce) with sausage and wild Italian broccoli (friarielli).";
                  let p22 = document.createElement("p");
                  p22.setAttribute("class", "menu__item-price");
                  p22.textContent = "$19";
               div21.appendChild(h21);
               div21.appendChild(p21);
               div21.appendChild(p22);
            div2.appendChild(img21);
            div2.appendChild(div21);

            let div3 = document.createElement("div");
            div3.setAttribute("class", "menu__item");
               let img31 = document.createElement("img");
               img31.setAttribute("src", pepperoni);
               img31.setAttribute("alt", "Pizza");
               img31.setAttribute("class", "menu__item-image");
               let div31 = document.createElement("div");
               div31.setAttribute("class", "menu__item-details");
                  let h31 = document.createElement("h3");
                  h31.setAttribute("class", "menu__item-title");
                  h31.textContent = "Pepperoni";
                  let p31 = document.createElement("p");
                  p31.setAttribute("class", "menu__item-description");
                  p31.textContent = "Thin crust with tomato sauce, mozzarella, and pepperoni.";
                  let p32 = document.createElement("p");
                  p32.setAttribute("class", "menu__item-price");
                  p32.textContent = "$16.50";
               div31.appendChild(h31);
               div31.appendChild(p31);
               div31.appendChild(p32);
            div3.appendChild(img31);
            div3.appendChild(div31);

            let div4 = document.createElement("div");
            div4.setAttribute("class", "menu__item");
               let img41 = document.createElement("img");
               img41.setAttribute("src", detroitRedTop);
               img41.setAttribute("alt", "Pizza");
               img41.setAttribute("class", "menu__item-image");
               let div41 = document.createElement("div");
               div41.setAttribute("class", "menu__item-details");
                  let h41 = document.createElement("h3");
                  h41.setAttribute("class", "menu__item-title");
                  h41.textContent = "Detroit Red Top";
                  let p41 = document.createElement("p");
                  p41.setAttribute("class", "menu__item-description");
                  p41.textContent = "Deep-dish with a crispy, caramelized crust and tomato sauce on top.";
                  let p42 = document.createElement("p");
                  p42.setAttribute("class", "menu__item-price");
                  p42.textContent = "$18";
               div41.appendChild(h41);
               div41.appendChild(p41);
               div41.appendChild(p42);
            div4.appendChild(img41);
            div4.appendChild(div41);

            let div5 = document.createElement("div");
            div5.setAttribute("class", "menu__item");
               let img51 = document.createElement("img");
               img51.setAttribute("src", margherita);
               img51.setAttribute("alt", "Pizza");
               img51.setAttribute("class", "menu__item-image");
               let div51 = document.createElement("div");
               div51.setAttribute("class", "menu__item-details");
                  let h51 = document.createElement("h3");
                  h51.setAttribute("class", "menu__item-title");
                  h51.textContent = "Margherita";
                  let p51 = document.createElement("p");
                  p51.setAttribute("class", "menu__item-description");
                  p51.textContent = "Classic with tomato sauce, mozzarella, and basil.";
                  let p52 = document.createElement("p");
                  p52.setAttribute("class", "menu__item-price");
                  p52.textContent = "$15";
               div51.appendChild(h51);
               div51.appendChild(p51);
               div51.appendChild(p52);
            div5.appendChild(img51);
            div5.appendChild(div51);

            let div6 = document.createElement("div");
            div6.setAttribute("class", "menu__item");
               let img61 = document.createElement("img");
               img61.setAttribute("src", sfincione);
               img61.setAttribute("alt", "Pizza");
               img61.setAttribute("class", "menu__item-image");
               let div61 = document.createElement("div");
               div61.setAttribute("class", "menu__item-details");
                  let h61 = document.createElement("h3");
                  h61.setAttribute("class", "menu__item-title");
                  h61.textContent = "Sfincione";
                  let p61 = document.createElement("p");
                  p61.setAttribute("class", "menu__item-description");
                  p61.textContent = "Thick crust with tomato sauce, onions, anchovies, oregano, and caciocavallo cheese.";
                  let p62 = document.createElement("p");
                  p62.setAttribute("class", "menu__item-price");
                  p62.textContent = "$15";
               div61.appendChild(h61);
               div61.appendChild(p61);
               div61.appendChild(p62);
            div6.appendChild(img61);
            div6.appendChild(div61);

            let div7 = document.createElement("div");
            div7.setAttribute("class", "menu__item");
               let img71 = document.createElement("img");
               img71.setAttribute("src", hawaiian);
               img71.setAttribute("alt", "Pizza");
               img71.setAttribute("class", "menu__item-image");
               let div71 = document.createElement("div");
               div71.setAttribute("class", "menu__item-details");
                  let h71 = document.createElement("h3");
                  h71.setAttribute("class", "menu__item-title");
                  h71.textContent = "Hawaiian";
                  let p71 = document.createElement("p");
                  p71.setAttribute("class", "menu__item-description");
                  p71.textContent = "A thin crust with tomato sauce, mozzarella, ham, and pineapple.";
                  let p72 = document.createElement("p");
                  p72.setAttribute("class", "menu__item-price");
                  p72.textContent = "$19";
               div71.appendChild(h71);
               div71.appendChild(p71);
               div71.appendChild(p72);
            div7.appendChild(img71);
            div7.appendChild(div71);

            let div8 = document.createElement("div");
            div8.setAttribute("class", "menu__item");
               let img81 = document.createElement("img");
               img81.setAttribute("src", chicagoClassic);
               img81.setAttribute("alt", "Pizza");
               img81.setAttribute("class", "menu__item-image");
               let div81 = document.createElement("div");
               div81.setAttribute("class", "menu__item-details");
                  let h81 = document.createElement("h3");
                  h81.setAttribute("class", "menu__item-title");
                  h81.textContent = "Chicago Classic";
                  let p81 = document.createElement("p");
                  p81.setAttribute("class", "menu__item-description");
                  p81.textContent = "Deep-dish with sausage, pepperoni, onions, peppers, and a rich tomato sauce.";
                  let p82 = document.createElement("p");
                  p82.setAttribute("class", "menu__item-price");
                  p82.textContent = "$17.50";
               div81.appendChild(h81);
               div81.appendChild(p81);
               div81.appendChild(p82);
            div8.appendChild(img81);
            div8.appendChild(div81);

         div.appendChild(div1);
         div.appendChild(div2);
         div.appendChild(div3);
         div.appendChild(div4);
         div.appendChild(div5);
         div.appendChild(div6);
         div.appendChild(div7);
         div.appendChild(div8);
      this.content.appendChild(div);
   }
};